apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview-service
  template:
    metadata:
      labels:
        app: interview-service
    spec:
      containers:
      - name: interview-service
        image: gograbjob/interview-service:10.0.0.1
        ports:
        - containerPort: 8500
